elasticsearch.host: localhost
elasticsearch.port: 9300
elasticsearch.cluster: elasticsearch
elasticsearch.alias: facilities
elasticsearch.doctype: facility
#
elasticsearch.index.settings: config/cals/facility/facility.settings.json
elasticsearch.document.mapping: config/cals/facility/facility.mapping.json
#
elasticsearch.xpack.user: elastic
elasticsearch.xpack.password: changeme
