//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.03.14 at 03:14:29 PM PDT
//


package mqcap.xsd;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for singleValColType complex type.
 * </p>
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * </p>
 * 
 * <pre>
 * &lt;complexType name="singleValColType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="smallint"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;smallint"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="integer"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;integer"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bigint"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;bigint"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="float"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;float"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="real"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;real"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="double"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;double"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="decimal"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;decimal"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="decfloat"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;decfloat"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="date"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;date"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="time"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;time"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="timestamp"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;timestamp"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="char"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;char"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="varchar"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;varchar"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longvarchar"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;longvarchar"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bitchar"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;bitchar"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bitvarchar"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;bitvarchar"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bitlongvarchar"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;bitlongvarchar"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="graphic"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;graphic"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vargraphic"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;vargraphic"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longvargraphic"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;longvargraphic"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rowid"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;rowid"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="blob"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;blob"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="clob"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;clob"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dbclob"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;dbclob"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="xml"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;&gt;xml"&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{}colAttrGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleValColType",
    propOrder = {"smallint", "integer", "bigint", "_float", "real", "_double", "decimal",
        "decfloat", "date", "time", "timestamp", "_char", "varchar", "longvarchar", "bitchar",
        "bitvarchar", "bitlongvarchar", "graphic", "vargraphic", "longvargraphic", "rowid", "blob",
        "clob", "dbclob", "xml"})
public class SingleValColType {

  @XmlElementRef(name = "smallint", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Smallint> smallint;
  @XmlElementRef(name = "integer", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Integer> integer;
  @XmlElementRef(name = "bigint", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Bigint> bigint;
  @XmlElementRef(name = "float", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Float> _float;
  @XmlElementRef(name = "real", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Real> real;
  @XmlElementRef(name = "double", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Double> _double;
  @XmlElementRef(name = "decimal", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Decimal> decimal;
  @XmlElementRef(name = "decfloat", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Decfloat> decfloat;
  @XmlElementRef(name = "date", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Date> date;
  @XmlElementRef(name = "time", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Time> time;
  @XmlElementRef(name = "timestamp", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Timestamp> timestamp;
  @XmlElementRef(name = "char", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Char> _char;
  @XmlElementRef(name = "varchar", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Varchar> varchar;
  @XmlElementRef(name = "longvarchar", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Longvarchar> longvarchar;
  @XmlElementRef(name = "bitchar", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Bitchar> bitchar;
  @XmlElementRef(name = "bitvarchar", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Bitvarchar> bitvarchar;
  @XmlElementRef(name = "bitlongvarchar", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Bitlongvarchar> bitlongvarchar;
  @XmlElementRef(name = "graphic", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Graphic> graphic;
  @XmlElementRef(name = "vargraphic", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Vargraphic> vargraphic;
  @XmlElementRef(name = "longvargraphic", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Longvargraphic> longvargraphic;
  @XmlElementRef(name = "rowid", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Rowid> rowid;
  @XmlElementRef(name = "blob", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Blob> blob;
  @XmlElementRef(name = "clob", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Clob> clob;
  @XmlElementRef(name = "dbclob", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Dbclob> dbclob;
  @XmlElementRef(name = "xml", type = JAXBElement.class, required = false)
  protected JAXBElement<SingleValColType.Xml> xml;
  @XmlAttribute(name = "name", required = true)
  protected String name;
  @XmlAttribute(name = "isKey")
  protected Boolean isKey;
  @XmlAttribute(name = "invalidData")
  protected Boolean invalidData;
  @XmlAttribute(name = "rawData")
  protected Boolean rawData;

  /**
   * Gets the value of the smallint property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Smallint }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Smallint> getSmallint() {
    return smallint;
  }

  /**
   * Sets the value of the smallint property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Smallint }{@code >}
   * 
   */
  public void setSmallint(JAXBElement<SingleValColType.Smallint> value) {
    this.smallint = value;
  }

  /**
   * Gets the value of the integer property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Integer }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Integer> getInteger() {
    return integer;
  }

  /**
   * Sets the value of the integer property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Integer }{@code >}
   * 
   */
  public void setInteger(JAXBElement<SingleValColType.Integer> value) {
    this.integer = value;
  }

  /**
   * Gets the value of the bigint property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Bigint }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Bigint> getBigint() {
    return bigint;
  }

  /**
   * Sets the value of the bigint property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Bigint }{@code >}
   * 
   */
  public void setBigint(JAXBElement<SingleValColType.Bigint> value) {
    this.bigint = value;
  }

  /**
   * Gets the value of the float property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Float }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Float> getFloat() {
    return _float;
  }

  /**
   * Sets the value of the float property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Float }{@code >}
   * 
   */
  public void setFloat(JAXBElement<SingleValColType.Float> value) {
    this._float = value;
  }

  /**
   * Gets the value of the real property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Real }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Real> getReal() {
    return real;
  }

  /**
   * Sets the value of the real property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Real }{@code >}
   * 
   */
  public void setReal(JAXBElement<SingleValColType.Real> value) {
    this.real = value;
  }

  /**
   * Gets the value of the double property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Double }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Double> getDouble() {
    return _double;
  }

  /**
   * Sets the value of the double property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Double }{@code >}
   * 
   */
  public void setDouble(JAXBElement<SingleValColType.Double> value) {
    this._double = value;
  }

  /**
   * Gets the value of the decimal property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Decimal }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Decimal> getDecimal() {
    return decimal;
  }

  /**
   * Sets the value of the decimal property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Decimal }{@code >}
   * 
   */
  public void setDecimal(JAXBElement<SingleValColType.Decimal> value) {
    this.decimal = value;
  }

  /**
   * Gets the value of the decfloat property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Decfloat }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Decfloat> getDecfloat() {
    return decfloat;
  }

  /**
   * Sets the value of the decfloat property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Decfloat }{@code >}
   * 
   */
  public void setDecfloat(JAXBElement<SingleValColType.Decfloat> value) {
    this.decfloat = value;
  }

  /**
   * Gets the value of the date property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Date }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Date> getDate() {
    return date;
  }

  /**
   * Sets the value of the date property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Date }{@code >}
   * 
   */
  public void setDate(JAXBElement<SingleValColType.Date> value) {
    this.date = value;
  }

  /**
   * Gets the value of the time property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Time }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Time> getTime() {
    return time;
  }

  /**
   * Sets the value of the time property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Time }{@code >}
   * 
   */
  public void setTime(JAXBElement<SingleValColType.Time> value) {
    this.time = value;
  }

  /**
   * Gets the value of the timestamp property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Timestamp }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Timestamp> getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the timestamp property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Timestamp }{@code >}
   * 
   */
  public void setTimestamp(JAXBElement<SingleValColType.Timestamp> value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the char property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Char }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Char> getChar() {
    return _char;
  }

  /**
   * Sets the value of the char property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Char }{@code >}
   * 
   */
  public void setChar(JAXBElement<SingleValColType.Char> value) {
    this._char = value;
  }

  /**
   * Gets the value of the varchar property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Varchar }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Varchar> getVarchar() {
    return varchar;
  }

  /**
   * Sets the value of the varchar property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Varchar }{@code >}
   * 
   */
  public void setVarchar(JAXBElement<SingleValColType.Varchar> value) {
    this.varchar = value;
  }

  /**
   * Gets the value of the longvarchar property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Longvarchar }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Longvarchar> getLongvarchar() {
    return longvarchar;
  }

  /**
   * Sets the value of the longvarchar property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Longvarchar }{@code >}
   * 
   */
  public void setLongvarchar(JAXBElement<SingleValColType.Longvarchar> value) {
    this.longvarchar = value;
  }

  /**
   * Gets the value of the bitchar property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Bitchar }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Bitchar> getBitchar() {
    return bitchar;
  }

  /**
   * Sets the value of the bitchar property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Bitchar }{@code >}
   * 
   */
  public void setBitchar(JAXBElement<SingleValColType.Bitchar> value) {
    this.bitchar = value;
  }

  /**
   * Gets the value of the bitvarchar property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Bitvarchar }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Bitvarchar> getBitvarchar() {
    return bitvarchar;
  }

  /**
   * Sets the value of the bitvarchar property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Bitvarchar }{@code >}
   * 
   */
  public void setBitvarchar(JAXBElement<SingleValColType.Bitvarchar> value) {
    this.bitvarchar = value;
  }

  /**
   * Gets the value of the bitlongvarchar property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Bitlongvarchar }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Bitlongvarchar> getBitlongvarchar() {
    return bitlongvarchar;
  }

  /**
   * Sets the value of the bitlongvarchar property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Bitlongvarchar }{@code >}
   * 
   */
  public void setBitlongvarchar(JAXBElement<SingleValColType.Bitlongvarchar> value) {
    this.bitlongvarchar = value;
  }

  /**
   * Gets the value of the graphic property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Graphic }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Graphic> getGraphic() {
    return graphic;
  }

  /**
   * Sets the value of the graphic property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Graphic }{@code >}
   * 
   */
  public void setGraphic(JAXBElement<SingleValColType.Graphic> value) {
    this.graphic = value;
  }

  /**
   * Gets the value of the vargraphic property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Vargraphic }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Vargraphic> getVargraphic() {
    return vargraphic;
  }

  /**
   * Sets the value of the vargraphic property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Vargraphic }{@code >}
   * 
   */
  public void setVargraphic(JAXBElement<SingleValColType.Vargraphic> value) {
    this.vargraphic = value;
  }

  /**
   * Gets the value of the longvargraphic property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Longvargraphic }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Longvargraphic> getLongvargraphic() {
    return longvargraphic;
  }

  /**
   * Sets the value of the longvargraphic property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Longvargraphic }{@code >}
   * 
   */
  public void setLongvargraphic(JAXBElement<SingleValColType.Longvargraphic> value) {
    this.longvargraphic = value;
  }

  /**
   * Gets the value of the rowid property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Rowid }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Rowid> getRowid() {
    return rowid;
  }

  /**
   * Sets the value of the rowid property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Rowid }{@code >}
   * 
   */
  public void setRowid(JAXBElement<SingleValColType.Rowid> value) {
    this.rowid = value;
  }

  /**
   * Gets the value of the blob property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Blob }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Blob> getBlob() {
    return blob;
  }

  /**
   * Sets the value of the blob property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Blob }{@code >}
   * 
   */
  public void setBlob(JAXBElement<SingleValColType.Blob> value) {
    this.blob = value;
  }

  /**
   * Gets the value of the clob property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Clob }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Clob> getClob() {
    return clob;
  }

  /**
   * Sets the value of the clob property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Clob }{@code >}
   * 
   */
  public void setClob(JAXBElement<SingleValColType.Clob> value) {
    this.clob = value;
  }

  /**
   * Gets the value of the dbclob property.
   * 
   * @return possible object is {@link JAXBElement
   *         }{@code <}{@link SingleValColType.Dbclob }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Dbclob> getDbclob() {
    return dbclob;
  }

  /**
   * Sets the value of the dbclob property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Dbclob }{@code >}
   * 
   */
  public void setDbclob(JAXBElement<SingleValColType.Dbclob> value) {
    this.dbclob = value;
  }

  /**
   * Gets the value of the xml property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link SingleValColType.Xml }{@code >}
   * 
   */
  public JAXBElement<SingleValColType.Xml> getXml() {
    return xml;
  }

  /**
   * Sets the value of the xml property.
   * 
   * @param value allowed object is {@link JAXBElement
   *        }{@code <}{@link SingleValColType.Xml }{@code >}
   * 
   */
  public void setXml(JAXBElement<SingleValColType.Xml> value) {
    this.xml = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the isKey property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public boolean isIsKey() {
    if (isKey == null) {
      return false;
    } else {
      return isKey;
    }
  }

  /**
   * Sets the value of the isKey property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setIsKey(Boolean value) {
    this.isKey = value;
  }

  /**
   * Gets the value of the invalidData property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public boolean isInvalidData() {
    if (invalidData == null) {
      return false;
    } else {
      return invalidData;
    }
  }

  /**
   * Sets the value of the invalidData property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setInvalidData(Boolean value) {
    this.invalidData = value;
  }

  /**
   * Gets the value of the rawData property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public boolean isRawData() {
    if (rawData == null) {
      return false;
    } else {
      return rawData;
    }
  }

  /**
   * Sets the value of the rawData property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setRawData(Boolean value) {
    this.rawData = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;bigint"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Bigint {

    @XmlValue
    protected long value;

    /**
     * Gets the value of the value property.
     * 
     * @return value
     */
    public long getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value value
     */
    public void setValue(long value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;bitchar"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Bitchar {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;bitlongvarchar"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Bitlongvarchar {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;bitvarchar"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Bitvarchar {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;blob"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Blob {

    @XmlValue
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public byte[] getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(byte[] value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;char"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Char {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;clob"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Clob {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;date"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Date {

    @XmlValue
    protected XMLGregorianCalendar value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setValue(XMLGregorianCalendar value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;dbclob"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Dbclob {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;decfloat"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Decfloat {

    @XmlValue
    protected BigDecimal value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setValue(BigDecimal value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;decimal"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Decimal {

    @XmlValue
    protected BigDecimal value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setValue(BigDecimal value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;double"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Double {

    @XmlValue
    protected double value;

    /**
     * Gets the value of the value property.
     * 
     * @return value
     */
    public double getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value value
     */
    public void setValue(double value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;float"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Float {

    @XmlValue
    protected float value;

    /**
     * Gets the value of the value property.
     * 
     * @return value
     */
    public float getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value value
     */
    public void setValue(float value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;graphic"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Graphic {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;integer"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Integer {

    @XmlValue
    protected BigInteger value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setValue(BigInteger value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;longvarchar"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Longvarchar {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;longvargraphic"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Longvargraphic {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;real"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Real {

    @XmlValue
    protected float value;

    /**
     * Gets the value of the value property.
     * 
     * @return value
     */
    public float getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value value
     */
    public void setValue(float value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;rowid"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Rowid {

    @XmlValue
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public byte[] getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(byte[] value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;smallint"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Smallint {

    @XmlValue
    protected short value;

    /**
     * Gets the value of the value property.
     * 
     * @return value
     */
    public short getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value value
     */
    public void setValue(short value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;time"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Time {

    @XmlValue
    protected XMLGregorianCalendar value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setValue(XMLGregorianCalendar value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;timestamp"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Timestamp {

    @XmlValue
    protected XMLGregorianCalendar value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setValue(XMLGregorianCalendar value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;varchar"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Varchar {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;vargraphic"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Vargraphic {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * </p>
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * </p>
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;simpleContent&gt;
   *     &lt;extension base="&lt;&gt;xml"&gt;
   *     &lt;/extension&gt;
   *   &lt;/simpleContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"value"})
  public static class Xml {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

  }

}
