# The old "elasticsearch.host" and "elasticsearch.port" will still work but not required when "elasticsearch.nodes" is provided.
elasticsearch.host: 10.10.15.61
elasticsearch.port: 9300
elasticsearch.cluster: elasticsearch
#Comma "," separated List of host:port pairs. Example: host1:port1,host2:port2
elasticsearch.nodes: 10.10.15.61:9300,10.10.15.61:9300
elasticsearch.alias: people
#elasticsearch.alias: people-small
elasticsearch.doctype: person
