#Comma "," separated List of host:port pairs. Example: host1:port1,host2:port2
elasticsearch.nodes: localhost:9300
elasticsearch.alias: people-summary
elasticsearch.doctype: person-summary
elasticsearch.cluster: elasticsearch

# People summary index:
# elasticsearch.index.setting.file: /elasticsearch/setting/people-index-settings.json
# elasticsearch.document.mapping.file: /elasticsearch/mapping/map_person_summary.json

# X-Pack:
elasticsearch.xpack.user: elastic
elasticsearch.xpack.password: changeme

