elasticsearch.host: localhost
elasticsearch.port: 9200
elasticsearch.cluster: elasticsearch
elasticsearch.alias: people
elasticsearch.doctype: person
elasticsearch.nodes: localhost:9200

# People index:
elasticsearch.index.setting.file: /elasticsearch/setting/people-index-settings.json
elasticsearch.document.mapping.file: /elasticsearch/mapping/map_person_5x_snake.json

# X-Pack:
# elasticsearch.xpack.user: elastic
# elasticsearch.xpack.password: changeme

