elasticsearch.host: localhost
elasticsearch.port: 9300
elasticsearch.cluster: elasticsearch
#elasticsearch.alias: people-summary-small
elasticsearch.alias: people-summary
elasticsearch.doctype: person-summary


# People index:
# elasticsearch.index.setting.file: /elasticsearch/setting/people-index-settings.json
# elasticsearch.document.mapping.file: /elasticsearch/mapping/map_person_5x_snake.json

# People summary index:
# elasticsearch.index.setting.file: /elasticsearch/setting/people-index-settings.json
# elasticsearch.document.mapping.file: /elasticsearch/mapping/map_person_summary.json

# X-Pack:
# elasticsearch.xpack.user: neutron
# elasticsearch.xpack.password: neutron

