elasticsearch.host: localhost
elasticsearch.port: 9300
#elasticsearch.cluster: elasticsearch_CWS-NS3
elasticsearch.cluster: elasticsearch
elasticsearch.alias: people
elasticsearch.doctype: person

#elasticsearch.xpack.user: neutron
#elasticsearch.xpack.password: neutron

