elasticsearch.host: elasticsearch.preint.cwds.io
elasticsearch.port: 9300
elasticsearch.cluster: es-preint
elasticsearch.additional.nodes:
  - elasticsearch.preint.cwds.io:9300
  - elasticsearch.preint.cwds.io:9300

# elasticsearch.alias: people_05-23-2017
elasticsearch.alias: people
elasticsearch.doctype: person
